config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles #generates CRUD

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Makes available to our views
  helper_method :current_user, :logged_in?

  def current_user
    # memoization, returned @current_user if it's already defined
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
    #   Note that I am using the method!! not the @current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 20)
  end

  def destroy
    @article.destroy
    flash[:success] = "Articles was successfully deleted"
    redirect_to articles_path
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit/delete your own article"
      redirect_to root_path
    end
  end

  private

  def set_article
    @article = Article.find params[:id]
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    # redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'There was something wrong with your login'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to login_path
  end

  private

  def login_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = "User was successfully created, welcome to the blog #{@user.username}"
        session[:user_id] = @user.id
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = "User was successfully updated"
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User was successfully destroyed'
    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to :back
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to :back
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article_author.haml
- author = article.user

= link_to gravatar_for(author, size:40), author
= author.username

app/views/articles/_articles.html.haml
.row
  .col
    -articles.each do |a|
      .card.mb-2
        .card-body
          .row
            .col
              %h5.card-title= a.title
            .col.text-right
              =a.user ? a.user.username : 'anon'
          %h6.card-subtitle.mb-2.text-muted=a.description
          - if a.user
            .row
              .col
                .card-text.small
                  Made:
                  =time_ago_in_words a.created_at
                  ago
                  ||
                  Updated:
                  =time_ago_in_words a.updated_at
                  ago
          -if logged_in? && (current_user == a.user || current_user.admin?)
            .row.mt-3
              .col
                = link_to "Show", article_path(a), class: 'btn btn-sm btn-outline-primary'
                = link_to "Edit", edit_article_path(a), class: 'btn btn-sm btn-outline-secondary'

app/views/articles/_form.html.haml
=render 'shared/errors', obj: @article
=form_for @article do |f|
  .form-row
    .col-auto
      .field
      = f.label :title
      = f.text_field :title, type: 'text', class: 'form-control', placeholder: 'An engaging title', autofocus: true
  .form-row.mt-2
    .col
      .field
        = f.label :description
        = f.text_area :description, class: 'form-control', placeholder: 'Write down some great ideas'
  .form-row.mt-3
    .col
      .actions
        .row
          .col.mr-auto
            = link_to "Cancel", @article.new_record? ? articles_path : article_path(@article), class: 'btn btn-outline-secondary'
          .col.text-right
            = f.submit class: 'btn btn-primary'

app/views/articles/edit.html.haml
%h1 Edit an article

=render "form"

app/views/articles/index.html.haml
.row
  .col
    %h1 Articles
  .col.text-right.mt-3
    =link_to "New Article", new_article_path, class: 'btn btn-primary' if logged_in?

=render 'articles', articles: @articles

-# this totally isn't centered. w/e
.row
  .col.text-center
    =will_paginate #@articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/articles/new.html.haml
%h1 Create an article

=render "form"

app/views/articles/show.html.haml
.row.mb-3
  .col
    =link_to "< Back to Articles", articles_path(@article), class: 'btn btn-link btn-sm'
.row
  .col
    %h2.display-3
      =@article.title
.row.mb-5
  .col-sm-2
    = render 'article_author', article: @article if @article.user
  .col
    - if logged_in? && (current_user == @article.user || current_user.admin?)
      =link_to "Edit", edit_article_path(@article), class: 'btn btn-outline-secondary btn-sm mr-3'
      =link_to "Delete", article_path(@article), method: :delete, data: {confirm: 'Are you sure you want to permanently delete this article?'}, class: 'btn btn-sm btn-outline-danger'
.row
  .col
    %p= @article.description

app/views/layouts/_messages.html.haml
.container
  .row
    .col
      - flash.each do |name, msg|
        %div{class: "alert alert-#{name}"}
          %a{href:"#", class:"close", 'data-dismiss':'alert'}
            &#215;
          =content_tag :div, msg, id:"flash_#{name}" if msg.is_a?(String)

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-5
  %a.navbar-brand{:href => root_path} My App
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        =link_to 'Home', root_path, class: 'nav-link'
      %li.nav-item
        =link_to 'Blog', articles_path, class: 'nav-link'
      %li.nav-item
        =link_to 'About', about_path, class: 'nav-link'
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Objects
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => articles_path} Articles
          %a.dropdown-item{:href => users_path} Users
          -#.dropdown-divider
          -#%a.dropdown-item{:href => "#"} Something else here
      -#%li.nav-item
      -#  %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
    %ul.navbar-nav.my-lg-0
      -if !logged_in?
        %li.nav-item
          =link_to 'Login', login_path, class: 'nav-link'
        %li.nav-item
          =link_to 'Signup', signup_path, class: 'nav-link'
      -else
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            ="Hi, #{current_user.username}"
          .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %a.dropdown-item{href: user_path(current_user)}
              View Profile
              = content_tag :span, "admin", class: 'badge badge-dark mr-1' if current_user.admin?
        %li.nav-item
          =link_to 'Logout', logout_path, method: :delete, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %title AlphaBlog
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render 'layouts/nav'
  = render 'layouts/messages'
.container
  = yield

app/views/pages/about.html.haml
.container
  .row
    .col
      %h1 About!
  .row
    .col
      %p Some stuff about stuff

app/views/pages/home.html.haml
.container.text-center
  .row
    .col
      =image_tag 'me.png', class: 'rounded-circle', width: '200px'
  .row.mt-5
    .col
      %h1 Welcome!
      %p There isn't much to see yet but just you wait :)

app/views/shared/_errors.html.haml
-if obj.errors.any?
  .alert.alert-warning
    .alert-heading
      %h4
        = pluralize(obj.errors.count, 'error')
        prohibited this article from being saved
      %hr
      %p
        %ul
        -obj.errors.full_messages.each do |msg|
          %li
            =msg

app/views/users/_form.html.haml
= form_for @user do |f|
  =render 'shared/errors', obj: @user
  .form-row
    .col-auto
      = f.label :username
      .input-group
        .input-group-prepend
          .input-group-text @
        = f.text_field :username, type: 'text', class: 'form-control', placeholder: 'awesome', autofocus: true
    .col
      .field
        = f.label :email
        = f.text_field :email, class: 'form-control', placeholder: 'me@awesome.com'
  .form-row
    .col
      .field
        = f.label :password
        = f.password_field :password, class: 'form-control', placeholder: 'Enter a good one'
  .form-row.mt-3
    .col
      .actions
        .row
          .col.mr-auto
            = link_to "Cancel", @user.new_record? ? users_path : user_path(@user), class: 'btn btn-outline-secondary'
          .col.text-right
            = f.submit class: 'btn btn-primary'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

app/views/users/index.html.haml
.row
  .col
    %h1 Users
  .col.text-right.mt-3
    =link_to "New User", signup_path, class: 'btn btn-primary' if logged_in?

.row
  .col
    - @users.each do |user|
      .card.mb-2
        .card-body
          .row
            .col.mr-auto
              .row.mb-2
                .col
                  %h5.card-title= user.username
              .row
                .col
                  %h6.card-subtitle.mb-2.text-muted=user.email
                  .card-text.small
                    Articles
                    %span.badge.badge-primary= user.articles.size
              -#      todo make this a link later
              -if logged_in? && current_user == user
                .row.mt-3
                  .col
                    = link_to "Show", user_path(user), class: 'btn btn-sm btn-outline-primary'
                    = link_to "Edit", edit_user_path(user), class: 'btn btn-sm btn-outline-secondary'
            .col.text-right
              = link_to gravatar_for(user, size:80), user

app/views/users/new.html.haml
%h1 New user

= render 'form'

app/views/users/show.html.haml
%p#notice= notice
.row.text-center
  .col
    =gravatar_for @user, size:150
.row.text-center.mt-5.mb-5
  .col
    %h2= @user.username
    %p= @user.email
    = link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-primary'
    = link_to 'Delete', user_path(@user), method: :delete, class: 'btn btn-outline-danger', data: {confirm: 'Are you sure you want to delete this user'} if logged_in? && current_user.admin?

=render 'articles/articles', articles: @user.articles